test/test.py|220 col 70 error| Call to untyped function "test" in typed context  [no-untyped-call]
test/subfolder/error.py|282 error| Function "datetime.datetime.date" is not valid as a type  [valid-type]
test/subfolder/bar.py|282 n| Perhaps you need "Callable[...]" or a callback protocol?
test/test/foo.py|35 col 5 error| Function is missing a type annotation for one or more arguments  [no-untyped-def]
test/subfolder/syntax_error.py|1 col 5 error| invalid syntax
